(()=>{'use strict';
// Frozen presentation only: no Wix backend, membership, checkout, analytics or forms.
const menu=document.querySelector('nav [data-index="__more__"] [aria-haspopup]');
const drop=document.querySelector('nav [id$="dropWrapper"]');
if(menu&&drop){const toggle=(open)=>{menu.setAttribute('aria-expanded',String(open));drop.dataset.dropdownShown=String(open);drop.style.display=open?'block':'none';drop.style.visibility=open?'visible':'hidden';drop.style.opacity=open?'1':'0';};toggle(false);menu.addEventListener('click',()=>toggle(menu.getAttribute('aria-expanded')!=='true'));menu.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();menu.click();}if(e.key==='Escape')toggle(false);});document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!drop.contains(e.target))toggle(false);});}
const lang=document.querySelector('[data-testid="languages-dropdown-handle"]'), langmenu=document.querySelector('#comp-kx06xcdz-dropdown-menu');
if(lang&&langmenu){langmenu.hidden=true;lang.addEventListener('click',()=>{langmenu.hidden=!langmenu.hidden;lang.setAttribute('aria-expanded',String(!langmenu.hidden));});document.addEventListener('click',e=>{if(!lang.contains(e.target)&&!langmenu.contains(e.target)){langmenu.hidden=true;lang.setAttribute('aria-expanded','false');}});}
document.querySelectorAll('[data-hook="accordion-item-header"]').forEach(b=>{let a=document.getElementById(b.getAttribute('aria-controls'));if(!a)return;a.hidden=true;a.style.display='none';b.setAttribute('aria-expanded','false');b.addEventListener('click',()=>{let open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));a.hidden=!open;a.setAttribute('aria-hidden',String(!open));a.style.display=open?'block':'none';const wrap=b.nextElementSibling;if(wrap){wrap.hidden=!open;wrap.style.height=open?'auto':'0';wrap.style.overflow=open?'visible':'hidden';}a.style.height='auto';a.style.maxHeight='none';a.style.opacity='1';a.style.visibility='visible';});});
const tabs=[...document.querySelectorAll('[data-hook^="tab-item-"]')];const panels=[...document.querySelectorAll('[data-archive-faq-panel]')];
if(panels.length)tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{tabs.forEach((t,j)=>{t.setAttribute('aria-selected',String(i===j));t.dataset.tabActive=String(i===j);t.classList.toggle('oGtN3P6--isActive',i===j);});panels.forEach((p,j)=>p.hidden=i!==j);const label=document.querySelector('[role=tabpanel]');if(label){label.removeAttribute('aria-labelledby');label.setAttribute('aria-label',tab.textContent.trim());}});tab.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();tab.click();}});});
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>e.preventDefault()));
document.querySelectorAll('a[aria-disabled="true"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
document.querySelectorAll('video').forEach(v=>{v.muted=true;v.play().catch(()=>{});});
})();
